### ISSUE TITLE
Improve Design of Navbar

### ISSUE THREAD

**Issue by jatin00000** [Sajiyah-Salat/BlogWeb#1]
I want to improve the overall design of Navbar. Making it more attractive.
Please assign me this issue.

**Comment by Sajiyah-Salat** [comment]
This issue is assigned to @jatin00000. Best of luck!

**Comment by jatin00000** [comment]
Done!! Please review and accept my Pull Request https://github.com/Sajiyah-Salat/BlogWeb/pull/15
