### ISSUE TITLE
Improving Design of Home Page

### ISSUE THREAD

**Issue by Kritika30032002** [Sajiyah-Salat/BlogWeb#24]
Improving Design of Home Page using CSS effects

Assign this issue to me!

**Comment by gauravsharmatheofficial** [comment]
I can improve the design of home Page. Plz assign this issue to me and add hacktoberfest and hacktoberfest2022 label to it.

**Comment by Kritika30032002** [comment]
> Improving Design of Home Page using CSS effects
> 
> Assign this issue to me!

@Sajiyah-Salat Assign this to me!

**Comment by Kritika30032002** [comment]
@Sajiyah-Salat image folder is not present when I forked you repo . therefore you website is looking completely different.
Is this a mistake or what? 

![image](https://user-images.githubusercontent.com/83400697/196908783-2f569e66-2ae8-43c6-b6c3-0c7fc2faa80f.png)

**Comment by Sajiyah-Salat** [comment]
It's my mistake The website you see is old version of current website..I deleted css and IMG folder accidentally

**Comment by Kritika30032002** [comment]
> It's my mistake The website you see is old version of current website..I deleted css and IMG folder accidentally

Its okay No problem I can work on CSS file too.

**Comment by Sajiyah-Salat** [comment]
Yeah sure...Best of luck for that

**Comment by gauravsharmatheofficial** [comment]
what I have to do?

**Comment by gauravsharmatheofficial** [comment]
> @Sajiyah-Salat image folder is not present when I forked you repo . therefore you website is looking completely different. Is this a mistake or what?
> 
> ![image](https://user-images.githubusercontent.com/83400697/196908783-2f569e66-2ae8-43c6-b6c3-0c7fc2faa80f.png)

I am improving this home page design

**Comment by Sajiyah-Salat** [comment]
Yeah! Go ahead
