### ISSUE TITLE
Adding About Page

### ISSUE THREAD

**Issue by Kritika30032002** [Sajiyah-Salat/BlogWeb#25]
Adding about page for website

Assign this issue to me!

**Comment by to-program-khushi-jain** [comment]
Can you assign this issue to me?

**Comment by gauravsharmatheofficial** [comment]
hey! @Sajiyah-Salat 
i wanna work on it
can you please assign it to me and add hacktoberfest and hacktoberfest2022 label to it

**Comment by rohitkori** [comment]
@Sajiyah-Salat can you please assign it to me

**Comment by Sajiyah-Salat** [comment]
hey, @Kritika30032002, @Kritika30032002, @gauravsharmatheofficial, @rohitkori. I would like you guys to work on my CSS issue as I can only add about page after that. Hope you Understand.
Thank you.

**Comment by Kritika30032002** [comment]
> hey, @Kritika30032002, @Kritika30032002, @gauravsharmatheofficial, @rohitkori. I would like you guys to work on my CSS issue as I can only add about page after that. Hope you Understand. Thank you.

yeah sure!!

**Comment by gauravsharmatheofficial** [comment]
> 
okay

**Comment by gauravsharmatheofficial** [comment]
> hey, @Kritika30032002, @Kritika30032002, @gauravsharmatheofficial, @rohitkori. I would like you guys to work on my CSS issue as I can only add about page after that. Hope you Understand. Thank you.

okay
