### ISSUE TITLE
Improving fonts and layout of "Contact me" page.

### ISSUE THREAD

**Issue by mayuri-agrawal** [Sajiyah-Salat/BlogWeb#26]
Want to improve the design of Contact Me page.
plz assign this issue to me .😊

**Comment by NabhiA** [comment]
Can I also work on this issue please.

**Comment by to-program-khushi-jain** [comment]
Hey I want to work on this issue

**Comment by Sajiyah-Salat** [comment]
hello @to-program-khushi-jain , @mayuri-agrawal , @NabhiA  are you there.... Would you like contribute in it?
