### ISSUE TITLE
I can improve navbar design and responsive also

### ISSUE THREAD

**Issue by DEV-Dhruva** [Sajiyah-Salat/BlogWeb#3]
Hey @Sajiyah-Salat , will you assign me this issue.

**Comment by Sajiyah-Salat** [comment]
Hey @DEV-Dhruva You are assigned to this issue. Best of luck!

**Comment by DEV-Dhruva** [comment]
Hey @Sajiyah-Salat , will you provide the css file because it is not present in code files.

**Comment by Kritika30032002** [comment]
Is this still available ?
May I contribute to this?
