### ISSUE TITLE
Making css file from scratch

### ISSUE THREAD

**Issue by Sajiyah-Salat** [Sajiyah-Salat/BlogWeb#32]
If you guys know a little bit of CSS you can contribute to this issue and get your pr accepted.

**Comment by Siddhesh172004** [comment]
I will try to do it. There is already a style.css file i would add css in that

**Comment by Siddhesh172004** [comment]
The website https://blogweb-c94c0.web.app/ has a  different output and when i forked the repo the output is something different.

This is the output which i got now. The logo is added by me.
![image](https://user-images.githubusercontent.com/84581657/196774221-26aae157-a286-46b9-9db4-0ac22ef1ac1d.png)

**Comment by Siddhesh172004** [comment]
I will add logo to navbar and align the input search and search btn properly. I hope that part should be focused now. Kindly assign me this issue.

**Comment by Sajiyah-Salat** [comment]
Wow! it looks wonderful. I know my live website and the current website doesn't look similar. I was sad enough to delete it. Thank you So much @Siddhesh172004 to solve this issue, but the work is still remaining. after the work got completed give me your LinkedIn Id and I will appreciate you publically.

**Comment by Kritika30032002** [comment]
May I contribute in this?

@Siddhesh172004 we can divide it in sections and both can make it done fastly.
If you agree then @Sajiyah-Salat can assign it to me also.

**Comment by Kritika30032002** [comment]
> Wow! it looks wonderful. I know my live website and the current website doesn't look similar. I was sad enough to delete it. Thank you So much @Siddhesh172004 to solve this issue, but the work is still remaining. after the work got completed give me your LinkedIn Id and I will appreciate you publically.

@Sajiyah-Salat CSS file is present , image folder is not .That's your website is looking like this!!

**Comment by Sajiyah-Salat** [comment]
This css file is made by someone else I mean it came as open source contribution. Ya IMG folder is not present but I can IMG folder if you want

**Comment by Kritika30032002** [comment]
@Siddhesh172004 We can divide the website in sections and both can work simultaneously on them. Let me know on which sections you are working or wants to work so that I can also start working on other sections.

**Comment by Kritika30032002** [comment]
@Sajiyah-Salat What should I do ? Do I wait for the reply of @Siddhesh172004 or start working on this? Let me know so that I can start!
