### ISSUE TITLE
Adding a light/dark mode

### ISSUE THREAD

**Issue by Pana1v** [Sajiyah-Salat/BlogWeb#4]
Please assign me this issue, to add a small button in the navigation bar, to toggle between modes

**Comment by Sajiyah-Salat** [comment]
Hey, @Pana1v You are assigned to this issue. Best of luck

**Comment by Pana1v** [comment]
hi, I have solved this issue. Added a dark mode/light mode toggle button.
Can you please add hacktober tag and accept my pull request.

**Comment by Pana1v** [comment]
thanks, can you accept my pull request please

**Comment by ravi4488** [comment]
@Sajiyah-Salat kindly assign me on this under Hacktoberfest 2022, I would like to work on this, adding a enhanced light/dark mode toggle button.
