### ISSUE TITLE
Poor user interface

### ISSUE THREAD

**Issue by ShailavMalik** [Sajiyah-Salat/BlogWeb#40]
@Sajiyah-Salat Can I work on it?

**Comment by Sajiyah-Salat** [comment]
Hey, Hope you know that I accidentally deleted my css file so live website and the code base is different so please run website on your local machine and then make changes..Best of luck

**Comment by ShailavMalik** [comment]
@Sajiyah-Salat do you want the code base to be matching with your live website or design the website my own way.
I can make it identical to your live website or can give website a different design
