### ISSUE TITLE
making of Contact Page

### ISSUE THREAD

**Issue by Sajiyah-Salat** [Sajiyah-Salat/BlogWeb#42]
As a contact page is a must on the website. You can work on it if you want. Your contributions is highly appreciated and those who make best contribution will get a shout out on my socials

**Comment by Sakshi-75** [comment]
Hi @Sajiyah-Salat , Can I work on this?
Also, can you provide the contact details to add on the page please?

**Comment by Sajiyah-Salat** [comment]
The contact should be simple https://blogweb-c94c0.web.app/ you can get idea from here also add my Twitter and LinkedIn handle and my email which is given below
 https://twitter.com/SajiyaSalat
https://www.linkedin.com/in/sajiya-salat-0a2a78245/
salatsajiya7.8.6@gmail.com
Best of Luck for that...

**Comment by Sakshi-75** [comment]
Hi @Sajiyah-Salat ,
I've raised a PR for this: #45 
Please review it.

**Comment by Sajiyah-Salat** [comment]
Sorry to say but a lot of work is remaining Don't add my socials directly use Twitter Gmail and LinkedIn icons also take ideas from this [contact page](https://blogweb-c94c0.web.app/contact.html) Copy pasting and twisting two lines don't make a contact page... Hope you understand Thanks for contributing... I Hope your skill will improve soon!
