### ISSUE TITLE
make this website eligible for good first issue

### ISSUE THREAD

**Issue by Sajiyah-Salat** [Sajiyah-Salat/BlogWeb#47]
I have come across [this](https://goodfirstissue.dev/) website and My Project is eligible to be added in the website but there are small things to be added. Any Code and Non-code contribution is appreciated.
Adding it's [GitHub repo link](https://github.com/deepsourcelabs/good-first-issue#adding-a-new-project) so you can get that.

**Comment by JanitaRiyaz** [comment]
i wanna do this.Assign this to me.

**Comment by Sajiyah-Salat** [comment]
Hey @JanitaRiyaz Are you working on this issue. please update me with that. 
Thank you.
