### ISSUE TITLE
Hi Sajiyah-salat, I have been exploring this repo and I saw it got so complex after several contribution

### ISSUE THREAD

**Issue by Girishbari** [Sajiyah-Salat/BlogWeb#49]
# I mean I am not able to understand what is the starting point for this project.
## So if you like I can help you with that by arranging all sorts of things as I understand

**Comment by Sajiyah-Salat** [comment]
Yeah, after so many contributions, it's kinda messed up. Please help me do that...

**Comment by Girishbari** [comment]
Where can I discuss some doubts with you, @Sajiyah-Salat

**Comment by Sajiyah-Salat** [comment]
We can discuss on [LinkedIn](https://www.linkedin.com/in/sajiya-salat-0a2a78245/)
